export const questionLabelMap = {
  accessibility: "How would you rate the overall accessibility?",
  parkingSuitable: "Was the parking suitable for your needs?",
  entranceAccessible: "Was the entrance easily accessible?",
  movement: "Could you move around inside without difficulties?",
  restroomsAccessible: "Were the restroom facilities accessible?",
  staffSupport: "Was the staff helpful and accommodating?",
  recommend: "Would you recommend this location to others with similar needs?",
  designatedSpot: "Was there a designated parking spot for people with disabilities?",
  sizeRating: "How would you rate the size of the parking space?",
  entranceAccessibleParking: "Was the entrance easily accessible from the parking area?",
  closeToEntrance: "Was the parking area close to the entrance?",
  pathWidthOK: "Were indoor pathways and corridors wide enough (min. 90 cm)?",
  elevatorOrRamp: "Were there elevators or ramps to navigate between floors?",
  elevatorAccessible: "If elevators, were they spacious and accessible?",
  obstaclesLevel: "Did you encounter any obstacles inside (e.g., narrow passages, furniture blocking the way)?",
  doorWidthOK: "Was the entrance door wide enough for a wheelchair (min. 85 cm)?",
  stepsOrThresholds: "Were there any steps or thresholds at the entrance?",
  rampAvailable: "If steps, was a ramp available?",
  doorType: "Was there an automatic or easy-to-open door?",
  accessibleRestroom: "Was there an accessible restroom available?",
  doorWidthOKRestroom: "Was the restroom door wide enough (min. 85 cm)?",
  spaceToManeuver: "Was there enough space to maneuver a wheelchair inside the restroom?",
  grabBarsInstalled: "Were grab bars installed near the toilet and sink?",
  sinkAccessible: "Was the sink accessible (e.g., appropriate height, space underneath)?",
  showerAvailable: "Was there an accessible shower facility (if applicable)?",
  knowledgeable: "Did the staff seem knowledgeable about accessibility needs?",
  assistanceWillingness: "Were they willing to provide assistance when needed?",
  communicationEffective: "Did they communicate effectively with you regarding your needs?"
};